name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main

      - run: sudo apt-get update && sudo apt-get install openjdk-8-jdk android-tools-adb bc bison curl flex g++-multilib gcc-multilib gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev git-core python3.8 libncurses5 --no-install-recommends

      - run: |
            export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
            curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
            sudo install -m 755 ${REPO} /bin/repo

      - run: git config --global --unset credential.helper

      - run: repo init --depth=1 --no-repo-verify -u https://android.googlesource.com/platform/manifest -b master -g default,-mips,-darwin,-notdefault

      - run: repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
